version: "3.7"
services:
  kurrelyy:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - '8080'
    ports:
      - '8080:8080'
    volumes:
      - ./src/:/home/node/app/src
    command: npm run dev
